### ISSUE TITLE
是否是使用 sequelize-cli初始的项目？

### ISSUE THREAD

**Issue by 1391020381** [k-water/egg-blog#3]
似乎没有迁移目录,migrations

**Comment by k-water** [comment]
手写的

**Comment by 1391020381** [comment]
了解。。。。。就是只用它的sequelize的model了？

**Comment by k-water** [comment]
可以这么理解，其他sequelize的功能没使用

**Comment by 1391020381** [comment]
在app.js中初始化数据库，app.model.sync({
        force: false,
      })
但是在model中数据库有依赖关联关系，但是此时一个数据库都木有，为啥不会报错？
